### ISSUE TITLE
Excellent work! I'm wondering how the context is fed into LLM. Do you input the whole paper directly into LLM? Or do you just input the abstract section of the paper into LLM?

### ISSUE THREAD

**Issue by wwngh1233** [taesiri/ArXivQA#1]

**Comment by taesiri** [comment]
Hello @wwngh1233 

The entire paper in LaTeX format is loaded, and then questions are asked. You can learn more and use a demo [here](https://huggingface.co/spaces/taesiri/ClaudeReadsArxiv).

**Comment by wwngh1233** [comment]
thx
